collections:
    authors:
        output: true

defaults:
    - scope:
        path: ""
        type: "authors"
      values:
        layout: "author"
    - scope:
        path: ""
        type: "posts"
      values:
        layout: "post"
    - scope:
        path: ""
      values:
        layout: "default"


# Misc
licence: CC-BY-CA
# Podcast
podcast:
  title: CDs sem Rótulo
  link: www.cdssemrotulo.com
  author: Paulo Rodrigo Martins
  art: https://archive.org/download/CDsSemRotulo/images/00-Cover-Original.png
  category: Education
  subcategories:
  - Personal Stories
  summary: >
    Este podcast é um conjunto de CDs encontrados em um baú antigo, mas sem nenhuma
    identificação sobre seus conteúdos. Eles parecem promissores e talvez sejam
    realmente um tesouro. Mas você só irá descobrir se o ouvi-los por completo.
    Este é um convite à reflexão, esteja preparado para mergulhar comigo em cada episódio.
